[package]
name = "emscripten-futures"
authors = ["Tamás Suhajda"]
version = "0.7.5"
edition = "2024"
description = "A local async executor and awaitable Emscripten operations for Rust WebAssembly applications"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/sutajo/emscripten-futures"
keywords = ["emscripten", "wasm", "async", "executor", "jspi"]
categories = ["asynchronous", "wasm"]
include = ["src/**", "build.rs", "README.md", "LICENSE-MIT", "LICENSE-APACHE"]

[workspace]
members = ["macros"]
exclude = ["tests/browser-bin"]

[package.metadata.docs.rs]
default-target = "wasm32-unknown-emscripten"
targets = ["wasm32-unknown-emscripten"]
features = ["spawn"]

[features]
default = ["spawn"]
spawn = []

[target.'cfg(target_os = "emscripten")'.dependencies]
emscripten_rs_sys = "0.4.0"
emscripten-futures-macros = { version = "0.1.2", path = "macros" }
futures = "0.3.34"
local-waker = "0.1.4"
send_wrapper = "0.6.0"

[target.'cfg(not(target_os = "emscripten"))'.dev-dependencies]
browser-test-bin = { path = "tests/browser-bin", artifact = "bin", target = "wasm32-unknown-emscripten" }
serde_json = "1.0"
tempfile = "3"
tiny_http = "0.12"

[[test]]
name = "mainloop"
harness = false
required-features = ["spawn"]
