[package]
name = "emscripten-futures-macros"
version = "0.1.2"
edition = "2024"
description = "Async test and benchmark attributes for emscripten-futures"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sutajo/emscripten-futures"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
